# Real Service API - Render.com Deployment Configuration

services:
  # Main API server
  - type: web
    name: real-service-api
    env: node
    # Completely isolated deployment approach with no dependencies on project code
    buildCommand: |
      # Run our deployment script to create an isolated production build
      bash ./deploy.sh
      # Move to the isolated deployment directory
      cd deploy
      # Install only the minimal required dependencies
      npm install
    startCommand: cd deploy && NODE_ENV=production node server.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: real-service-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_MAPBOX_TOKEN
        sync: false
    autoDeploy: false # Disable auto-deploy to ensure proper testing

databases:
  # PostgreSQL database
  - name: real-service-db
    plan: standard

# Additional environment variables can be set in the Render dashboard