services:
  # Main API server
  - type: web
    name: real-service-api
    env: node
    buildCommand: ./render-build.sh
    startCommand: node render-quick-fix.js
    healthCheckPath: /healthz
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: real-service-db
          property: connectionString
      # Removed hardcoded PORT - let Render assign it dynamically

databases:
  - name: real-service-db
    plan: starter