services:
  # Main API server
  - type: web
    name: real-service-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node start-production.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: real-service-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: real-service-db
    plan: starter